project:
  type: website
  output-dir: docs
  
website:
  title: "WERA 2024 Workshop - Intro to SQL for Education"
  navbar:
    left:
      - href: index.qmd
        text: Setup Instructions
      - href: WERA-2024-Intro-SQL.qmd
        text: Slide Deck

    tools:
      - icon: github
        href: https://github.com/jeff-p-stuinfo/wera-sql-site
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
format:
  html:
    theme: sandstone
    toc: true

editor: source

