project:
  type: website
  output-dir: docs
  
website:
  title: "WERA 2024 Workshop - Intro to SQL for Education"
  navbar:
    left:
      - href: index.qmd
        text: Workshop Home
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/jeff-p-stuinfo/wera-sql-site
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: sandstone
    toc: true

editor: source

